spring.application.name=mindmapper
server.port=9092

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mind_mapper-core
spring.datasource.username=postgres
spring.datasource.password=Nayan@2331
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresPlusDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Security Configuration
logging.level.org.springframework.security=DEBUG


# JWT Secret Key
jwt.secret.key=abcdREAFAFASFASFASFGER$#@%$#$^%^WEFEW757452456452135

#Oauth2 Configuration
##Gitlab
spring.security.oauth2.client.registration.gitlab.client-id=b8525bcf93fc49709923ea3d9119c3ecfdeba36ee35cdeb48b1a1f2b3b68fc34
spring.security.oauth2.client.registration.gitlab.client-secret=gloas-5e23617e64245833f4e40dc8b394176e0be79e2e7f44bb81cb452b6e51394511
spring.security.oauth2.client.registration.gitlab.scope=openid,read_user
spring.security.oauth2.client.registration.gitlab.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gitlab.redirect-uri=http://localhost:9092/login/oauth2/code/gitlab
spring.security.oauth2.client.provider.gitlab.authorization-uri=https://gitlab.com/oauth/authorize
spring.security.oauth2.client.provider.gitlab.token-uri=https://gitlab.com/oauth/token
spring.security.oauth2.client.provider.gitlab.issuer-uri=https://gitlab.com
spring.security.oauth2.client.provider.gitlab.user-info-uri=https://gitlab.com/oauth/userinfo
spring.security.oauth2.client.provider.gitlab.jwk-set-uri=https://gitlab.com/oauth/discovery/keys

logging.level.org.springframework.web=DEBUG
logging.level.com.mindmapper=DEBUG